# fly.toml app configuration file generated for storydots on 2023-05-11T23:18:54-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "storydots"
primary_region = "eze"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
